export const grammarTopics = {
  A1: [
    "Presente indicativo",
    "Essere e Avere",
    "Verbi modali (potere, volere, dovere)",
    "Stare + Gerundio",
    "Genere e numero dei nomi",
    "Articoli determinativi e indeterminativi",
    "Aggettivi qualificativi",
    "Aggettivi possessivi",
    "Aggettivi dimostrativi",
    "Preposizioni semplici",
    "Pronomi personali soggetto",
  ],
  A2: [
    "Passato Prossimo",
    "Imperfetto",
    "Futuro Semplice",
    "Imperativo",
    "Verbi riflessivi",
    "Pronomi diretti",
    "Pronomi indiretti",
    "Particelle 'ci' e 'ne'",
    "Preposizioni articolate",
    "Comparativi",
    "Avverbi di tempo e frequenza",
    "Congiunzioni coordinanti",
  ],
  B1: [
    "Condizionale Presente",
    "Congiuntivo Presente",
    "Congiuntivo Imperfetto",
    "Trapassato Prossimo",
    "Forma Passiva",
    "Pronomi relativi",
    "Pronomi combinati",
    "Periodo Ipotetico (1° e 2° tipo)",
    "Concordanza dei tempi all'indicativo",
    "Discorso indiretto",
    "Uso di 'si' impersonale e passivante",
    "Superlativo relativo e assoluto",
    "Formazione degli avverbi in '-mente'",
  ],
};
